title: "June Bash -- software developer, etc"
author: June Bash
email: junebash@pm.me
description: "June Bash is a software developer (iOS, games, generalist) and musician living in Bellingham, WA."
twitter: "@Junebash"
youtube: https://www.youtube.com/channel/UC2y-Ro0-_h4YW6dkJFegSWw
github: junebash
# baseurl:
excerpt_separator: <!--more-->
highlighter: rouge
sass:
  load_paths:
    - _sass
    - node_modules
assets: /assets
images: /assets/images
permalink: /blog/:slug/
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      author: June Bash
  -
    scope:
      type: posts
      path: ""
    values:
      layout: post
  -
    scope:
      path: ""
      type: "now-updates"
    values:
      layout: "now-update"
      description: "a brief summary of how I've been spending my time lately"
collections:
  games:
  films:
  concert-music:
  other-music:
  now-updates:
    output: true
    permalink: /now/:name/
plugins:
  - jekyll-feed
exclude:
  - temp_assets
  - node_modules
  - .DS_Store
  - .gitignore
  - wp-content
  - home
