title: "Jon Bash -- composer, sound designer, etc"
email: jonbashmusic@gmail.com
sass:
  load_paths:
    - _sass
    - node_modules
exclude: []
assets: /assets
images: /assets/images
defaults:
  -
    values:
      author: Jon Bash
      layout: default
gems:
  - jekyll-email-protect
exclude:
  - temp_assets
  - node_modules
