title: "Jon Bash -- composer, sound designer, etc"
author: Jon Bash
email: JonBashMusic@Gmail.com
twitter: "@jonbash"
mastodon: "@jonbash@mastodon.social"
youtube: jonbashjonbash
github: jonbash
baseurl: null
excerpt_separator: <!--more-->
sass:
  load_paths:
    - _sass
    - node_modules
assets: /assets
images: /assets/images
permalink: /blog/:slug/
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      type: posts
      path: ""
    values:
      layout: post
collections:
  - games
  - films
  - concert-music
  - other-music
plugins:
  - jekyll-feed
exclude:
  - temp_assets
  - node_modules
  - .DS_Store
  - .gitignore
  - wp-content
